// export const ENDPOINT = 'https://arch17-apis.herokuapp.com/api/'
// export const ENDPOINT = 'http://locahost:8000/api/'
export const SIGNUP_EMAIL_PASSWORD_REQUEST = 'SIGNUP_EMAIL_PASSWORD_REQUEST';
export const SIGNUP_EMAIL_PASSWORD_SUCCESS = 'SIGNUP_EMAIL_PASSWORD_SUCCESS';
export const SIGNUP_EMAIL_PASSWORD_FAIL = 'SIGNUP_EMAIL_PASSWORD_FAIL';

export const SIGNIN_EMAIL_PASSWORD_REQUEST = 'SIGNIN_EMAIL_PASSWORD_REQUEST';
export const SIGNIN_EMAIL_PASSWORD_SUCCESS = 'SIGNIN_EMAIL_PASSWORD_SUCCESS';
export const SIGNIN_EMAIL_PASSWORD_FAIL = 'SIGNIN_EMAIL_PASSWORD_FAIL';

export const SET_NAV_INFO = 'SET_NAV_INFO'
export const VANILLA_SIGNIN_EMAIL_PASSWORD_SUCCESS = 'VANILLA_SIGNIN_EMAIL_PASSWORD_SUCCESS'
export const FACEBOOK_SIGNUP_REQUEST_SUCCESS = "FACEBOOK_SIGNUP_REQUEST_SUCCESS"

export const GOOGLE_SIGNUP_REQUEST = 'GOOGLE_SIGNUP_REQUEST'
export const GOOGLE_SIGNUP_SUCCESS = 'GOOGLE_SIGNUP_SUCCESS'
export const POHONE_SIGNUP_REQUEST = 'POHONE_SIGNUP_REQUEST'
export const POHONE_SIGNUP_SUCCESS = 'POHONE_SIGNUP_SUCCESS'
export const TWITTER_SIGNUP_REQUEST = 'TWITTER_SIGNUP_REQUEST'
export const TWITTER_SIGNUP_SUCCESS = 'TWITTER_SIGNUP_SUCCESS'
export const PHONE_SIGNUP_REQUEST = 'PHONE_SIGNUP_REQUEST'
export const PHONE_SIGNUP_SUCCESS = 'PHONE_SIGNUP_SUCCESS'
export const NORMAL_SIGNUP_SUCEESS = 'NORMAL_SIGNUP_SUCEESS'
export const NORMAL_SIGNIN_SUCEESS = 'NORMAL_SIGNIN_SUCEESS'
export const LOGOUT = 'LOGOUT'
export const UPDATE_INFO = 'UPDATE_INFO'









